language: node_js
node_js:
  - stable
before_cache: npm prune
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: npm run test-ci
branches:
  only:
    - master
    - develop
# force container based infra
sudo: false
cache:
  directories:
    - node_modules
